server:
  port: 8080
spring:
  datasource:
    url: jdbc:hsqldb:file:./data/studentsdb;shutdown=true
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: SA
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
