CREATE TABLE groups (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        number VARCHAR(255) NOT NULL,
                        faculty VARCHAR(255) NOT NULL
);

CREATE TABLE students (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          middle_name VARCHAR(255),
                          birth_date DATE NOT NULL,
                          group_id BIGINT NOT NULL,
                          CONSTRAINT fk_group_id FOREIGN KEY (group_id)
                              REFERENCES groups(id)
                              ON DELETE RESTRICT
);
